pm/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^project/new', create_project, name='project-new'),
    url(r'^project/(?P<pk>\d+)$', project_detail, name='project-detail'),
    url(r'^person/(?P<pk>\d+)$', PersonDetailView.as_view(), name='person-detail'),
    url(r'^task/new$', create_task, name='task-new'),
    url(r'^task/edit$', edit_task, name='task-edit'),
    url(r'^get_users$', get_users, name='get-users'),
    url(r'^review/(?P<project>\d+)?$', reviews, name='reviews'),
]

projManager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pm/', include('pm.urls', namespace='pm')),
]

pm/models.py
from datetime import date, timedelta
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models


# Redefine the User model to use a cleaner name rather than the
# username itself, which may be difficult to interpret
def user_unicode_patch(self):
    return u'%s, %s (%s)' % (self.last_name, self.first_name, self.username)

User.__unicode__ = user_unicode_patch


class Group(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    internal = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name


class People(models.Model):
    name = models.OneToOneField(settings.AUTH_USER_MODEL)
    group = models.ForeignKey(Group)

    class Meta:
        unique_together = ('name', 'group',)
        permissions = (
            ('view_people', 'Can view people'),
            ('modify_people', 'Can create, edit, and delete people'),
        )

    def __unicode__(self):
        return "%s, %s (%s)" % (self.name.last_name, self.name.first_name, self.group.name)

    def full_name(self):
        return "%s %s" % (self.name.first_name, self.name.last_name)
        
    def full_name_lastnamefirst(self):
        return "%s, %s" % (self.name.last_name, self.name.first_name)
    
    def lead_count(self):
        return self.worker_set.filter(owner=True).count()

    def task_count(self):
        return TaskWorker.objects.filter(worker__person=self).count()

    def two_wk_task_count(self):
        return TaskWorker.objects.filter(worker__person=self, task__due_date__range=[
            date.today(),
            date.today() + timedelta(14)
        ]).count()


class Program(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        permissions = (
            ('modify_program', 'Can create, edit, and delete programs'),
        )

    def __unicode__(self):
        return self.name


class Project(models.Model):
    HIGH = 'HI'
    STANDARD = 'ST'
    LOW = 'LO'
    PRIORITY_CHOICES = (
        (HIGH, 'High'),
        (STANDARD, 'Standard'),
        (LOW, 'Low')
    )

    ACTIVE = 'A'
    ON_HOLD = 'O'
    WARRANTY = 'W'
    MAINTENANCE = 'M'
    COMPLETED = 'C'
    STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (ON_HOLD, 'On hold'),
        (WARRANTY, 'Warranty'),
        (MAINTENANCE, 'Maintenance'),
        (COMPLETED, 'Completed')
    )

    name = models.CharField(max_length=500)
    requester = models.ForeignKey(People, related_name="person_requester")
    project_manager = models.ForeignKey(People, related_name="person_project_manager")
    program = models.ForeignKey(Program)
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    start_date = models.DateField()
    due_date = models.DateField(null=True, blank=True)
    date_complete = models.DateField(null=True, blank=True)
    sharepoint_ticket = models.URLField(null=True, blank=True)
    priority = models.CharField(null=True, choices=PRIORITY_CHOICES, default=STANDARD, max_length=2)
    status = models.CharField(choices=STATUS_CHOICES, default=ACTIVE, max_length=1)

    class Meta:
        permissions = (
            ('view_project', 'Can view projects'),
            ('modify_project', 'Can create, edit, and delete projects'),
        )

    def __unicode__(self):
        return self.name

    def completed_tasks(self):
        """
        Return the number of completed tasks in a project.
        """
        return self.task_set.exclude(date_complete=None)

    def est_completion_date(self):
        """
        Iterate through the tasks in a project, return the latest due date as
        the project completion estimate. If no tasks are yet assigned, return
         "No Estimate".
        """
        if self.task_set.all().count() is 0:
            return "No estimate"
        else:
            due_dates = []
            for task in self.task_set.all():
                if task.due_date is None:
                    continue
                else:
                    due_dates.append(task.due_date)
            if len(due_dates) == 0:
                return "No estimate"
            else:
                return max(due_dates)
    
    def next_tasks(self):
        """
        Return a list of the next tasks due plus due dates.
        """
        due_date_list = self.task_set.exclude(due_date=None).values('due_date')  # min() returns a dict, pulling the datetime value out
        if not due_date_list:
            return due_date_list
        next_due_date = min(due_date_list)['due_date'] 
        return self.task_set.filter(due_date=next_due_date)


class Worker(models.Model):
    project = models.ForeignKey(Project)
    person = models.ForeignKey(People)
    date_added = models.DateField(auto_now_add=True)
    start_date = models.DateField(null=True, blank=True)
    date_complete = models.DateField(null=True, blank=True)
    percent_committed = models.IntegerField(null=True, blank=True)
    owner = models.BooleanField(default=False)

    class Meta:
        unique_together = ('project', 'person',)

    def __unicode__(self):
        return "%s (%s) - %s" % (self.person.full_name(), self.person.group.name, self.project.name)


class Task(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=500)
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    start_date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    date_complete = models.DateField(null=True, blank=True)
    status_on_hold = models.BooleanField(default=False)
    status_waiting = models.BooleanField(default=False)

    class Meta:
        unique_together = ('name', 'project',)
        permissions = (
            ('view_task', 'Can view tasks'),
            ('modify_task', 'Can create, edit, and delete tasks'),
        )

    def __unicode__(self):
        return "%s - %s" % (self.name, self.project.name)

    def status(self):
        if self.date_complete is not None:
            return 'Complete'
        elif self.status_waiting:
            return 'Waiting on\n external party'
        elif self.status_on_hold:
            return 'On hold'
        elif TaskDependency.objects.filter(blocked_task=self).filter(blocking_task__date_complete=None).exists():
            return 'Queued'
        else:
            return 'Active'


class TaskDependency(models.Model):
    blocking_task = models.ForeignKey(Task, related_name="blocking_task")
    blocked_task = models.ForeignKey(Task, related_name="blocked_task")

    class Meta:
        unique_together = ('blocking_task', 'blocked_task',)

    def __unicode__(self):
        return "%s - %s" % (self.blocking_task, self.blocked_task)


class TaskWorker(models.Model):
    task = models.ForeignKey(Task)
    worker = models.ForeignKey(Worker)

    class Meta:
        unique_together = ('task', 'worker',)

    def __unicode__(self):
        return "%s (%s) - %s - %s" % (self.worker.person.full_name(), self.worker.person.group.name, self.worker.project.name, self.task.name)


class Reviews(models.Model):
    VERY_POOR = 1
    POOR = 2
    AVERAGE = 3
    GOOD = 4
    VERY_GOOD = 5
    RATING_CHOICES = (
        (VERY_POOR, 'Very Poor'),
        (POOR, 'Poor'),
        (AVERAGE, 'Average'),
        (GOOD, 'Good'),
        (VERY_GOOD, 'Very Good')
    )

    rating = models.SmallIntegerField()
    comments = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return "Review"


class ProjectReviews(models.Model):
    review = models.ForeignKey(Reviews)
    project = models.ForeignKey(Project)

    class Meta:
        unique_together = ('review', 'project')

    def __unicode__(self):
        return "Review: %s" % self.project.name


class WorkerReviews(models.Model):
    review = models.ForeignKey(Reviews)
    worker = models.ForeignKey(Worker)

    class Meta:
        unique_together = ('review', 'worker')

    def __unicode__(self):
        return "Review: %s on %s" % (self.worker.person.full_name(), self.worker.project.name)

pm/forms.py
from django import forms
from django.db.models import Q
from pm.models import Program, Project, People, Task, Worker, TaskDependency, Reviews, ProjectReviews, WorkerReviews
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Div, Field, Fieldset, HTML


class ProjectForm(forms.Form):
    name = forms.CharField(max_length=500)
    requester = forms.ModelChoiceField(People.objects.all())
    project_manager = forms.ModelChoiceField(People.objects.filter(group__internal=True))
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 60}))
    start_date = forms.DateField()
    due_date = forms.DateField(required=False)
    date_complete = forms.DateField(required=False)
    sharepoint_ticket = forms.URLField(required=False)
    priority = forms.ChoiceField(choices=Project.PRIORITY_CHOICES, initial=Project.STANDARD)
    status = forms.ChoiceField(choices=Project.STATUS_CHOICES)
    program = forms.ModelChoiceField(Program.objects.all(), empty_label=None, initial="None")
    workers = forms.ModelMultipleChoiceField(queryset=People.objects.all())

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "create_project"
        self.helper.form_action = "pm:project-new"
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.layout = Layout(
            Div(
                Div(Field('name'), css_class='col-sm-6'),
                Div(Field('requester'), css_class='col-sm-3'),
                Div(Field('project_manager'), css_class='col-sm-3'),
                css_class='row',
            ),
            Div(
                Div(Field('description'), css_class='col-sm-6'),
                Div(
                    Div(
                        Div(Field('start_date'), css_class='col-sm-6 datemask'),
                        Div(Field('program'), css_class='col-sm-6'),
                        css_class='row',
                    ),
                    Div(
                        Div(Field('due_date'), css_class='col-sm-6 datemask'),
                        Div(Field('status'), css_class='col-sm-6'),
                        css_class='row',
                    ),
                    Div(
                        Div(Field('date_complete'), css_class='col-sm-6 datemask'),
                        Div(Field('priority'), css_class='col-sm-6'),
                        css_class='row',
                    ),
                    css_class='col-sm-6',
                ),
                css_class='row',
            ),
            Div(
                Div(Field('sharepoint_ticket'), css_class='col-sm-6'),
                Div(Field('workers'), css_class='col-sm-6'),
                css_class='row',
            )
        )


class TaskForm(forms.Form):
    project = forms.ModelChoiceField(queryset=Project.objects.all(), empty_label=None)
    name = forms.CharField()
    start_date = forms.DateField(input_formats=['%m-%d-%Y'])
    due_date = forms.DateField(input_formats=['%m-%d-%Y'], required=False)
    date_complete = forms.DateField(input_formats=['%m-%d-%Y'], required=False)
    status_on_hold = forms.BooleanField(required=False, label='On hold')
    status_waiting = forms.BooleanField(required=False, label='Waiting on external party')
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 60}), required=False)
    worker = forms.ModelMultipleChoiceField(queryset=People.objects.none())
    blocked_by = forms.ModelMultipleChoiceField(queryset=Task.objects.none(), required=False)
    pk = forms.IntegerField(required=False)

    def __init__(self, *args, **kwargs):
        self.project_id = kwargs.pop('project_id')
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['worker'].queryset = People.objects.filter(Q(worker__project=self.project_id) & Q(group__internal=True))
        self.fields['blocked_by'].queryset = Task.objects.filter(project=self.project_id)

        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.form_id = "create-task"
        self.helper.form_action = "pm:task-new"
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.layout = Layout(
            Div(
                Div(Field('name'), css_class='col-lg-3 col-sm-6'),
                Div(Field('start_date'), css_class='col-lg-3 col-sm-6 datemask'),
                Div(Field('due_date'), css_class='col-lg-3 col-sm-6 datemask'),
                Div(Field('status_on_hold'), Field('status_waiting'), css_class='col-lg-3 col-sm-6'),
                css_class='row',
            ),
            Div(
                Div(Field('description'), css_class='col-lg-3 col-sm-6'),
                Div(Field('worker'), css_class='col-lg-3 col-sm-6'),
                Div(Field('blocked_by'), css_class='col-lg-3 col-sm-6'),
                Div(Field('project'), css_class='col-lg-3 col-sm-6'),
                css_class='row',
            ),
        )


class ProjectReviewForm(forms.Form):
    project = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=Project.objects.none())
    rating = forms.ChoiceField(choices=Reviews.RATING_CHOICES, initial=Reviews.AVERAGE)
    comments = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 60}), required=False)

    def __init__(self, *args, **kwargs):
        p_pk = kwargs.pop('project')
        super(ProjectReviewForm, self).__init__(*args, **kwargs)
        p = Project.objects.get(pk=p_pk)
        self.fields['project'].queryset = p

        self.helper = FormHelper()
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(
                'Project review: %s' % p.name,
                Field('project'),
                Row(Div(HTML('<p>%s</p>' % p.description), css_class='col-sm-12')),
                Row(Div(Field('rating'), css_class='col-sm-4'), Div(Field('comments'), css_class='col-sm-8'))
            ),
        )


class WorkerReviewForm(forms.Form):
    worker = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=Worker.objects.none())
    rating = forms.ChoiceField(choices=Reviews.RATING_CHOICES, initial=Reviews.AVERAGE)
    comments = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 60}), required=False)

    def __init__(self, *args, **kwargs):
        w_pk = kwargs.pop('worker')
        super(WorkerReviewForm, self).__init__(*args, **kwargs)
        w = Worker.objects.get(pk=w_pk)
        self.fields['worker'].queryset = w

        tw = Task.objects.filter(Q(project=w.project) & Q(taskworker__worker=w))
        s = ""
        for t in tw:
            s += ("<li>%s (%s)</li>" % (t.name, t.description))

        self.helper = FormHelper()
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Fieldset(
                'Worker review: %s' % w.person.full_name(),
                Field('worker'),
                Row(Div(HTML("<ul>%s</ul>" % s), css_class='col-sm-12')),
                Row(Div(Field('rating'), css_class='col-sm-4'), Div(Field('comments'), css_class='col-sm-8'))
            ),
        )

pm/templates/pm/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

		<title>{% block title %}ProjectManager{% endblock %}</title>

        <link href="{% static 'pm/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'pm/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'pm/css/ionicons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'pm/css/AdminLTE.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'pm/css/select2.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'pm/css/datatables.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'pm/css/daterangepicker-bs3.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'pm/css/styles.css' %}" rel="stylesheet" type="text/css" />
        {% block custom_css %}{% endblock %}
	</head>
	<body class="skin-blue">
        <!-- top row header -->
        <header class="header">
            <a href="{% url 'pm:index' %}" class="logo">ProjManager</a>

            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="user user-menu dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span>{{ user.first_name }} {{ user.last_name }} <i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                 </li>
                             </ul>
                         </li>
                    </ul>
                </div>
            </nav>
        </header>

        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <section class="sidebar">
                    <ul class="sidebar-menu">
                        <li class="active">
                            <a href="{% url 'pm:index' %}">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                        <li class="treeview{% if project %} active{% endif %}">
                            <a href="#">
                                <i class="fa fa-list-alt"></i>
                                <span>Projects</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="{% url 'pm:project-new' %}"><i class="fa fa-plus-square-o"></i> New project</a></li>
                            {% for project in projects %}
                                <li><a href="{% url 'pm:project-detail' project.id %}"><i class="fa fa-angle-double-right"></i> {{ project.name }}</a></li>
                            {% endfor %}
                            </ul>
                        </li>
                        <li class="treeview{% if person %} active{% endif %}">
                            <a href="#">
                                <i class="fa fa-users"></i>
                                <span>People</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                            {% for person in peoples %}
                                <li><a href="{% url 'pm:person-detail' person.id %}"><i class="fa fa-angle-double-right"></i> {{ person.full_name_lastnamefirst }}</a></li>
                            {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </section>
            </aside>

            <!-- content -->
            <aside class="right-side">
                <section class="content-header">
                    <h1>{% block content-header %}{% endblock %}</h1>
                </section>
                <section class="content" id="{% block section_id %}{% endblock %}">
                    {% block content %}{% endblock %}
                </section>
            </aside>

        </div> <!-- wrapper -->

        <script type="text/javascript" src="{% static 'pm/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'pm/js/jquery.cookie.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'pm/js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'pm/js/custom.js' %}"></script>
        <script type="text/javascript" src="{% static 'pm/js/AdminLTE.js' %}"></script>
        <script type="text/javascript" src="{% static 'pm/js/jquery.inputmask.bundle.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pm/js/select2.js' %}"></script>
        <script type="text/javascript" src="{% static 'pm/js/datatables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pm/js/moment.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pm/js/daterangepicker.js' %}"></script>
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script type="text/javascript" src="{% static 'pm/js/html5shiv.min.js' %}"></script>
			<script type="text/javascript" src="{% static 'pm/js/respond.min.js' %}"></script>
		<![endif]-->
        <script type="text/javascript">{% block custom_js %}{% endblock %}</script>
	</body>
</html>

pm/templates/pm/index.html
{% extends "pm/base.html" %}

{% block title %}Project Listing{% endblock title %}

{% block content-header %}Dashboard{% endblock content-header %}

{% block section_id %}index{% endblock section_id %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="box box-solid box-primary">
            <div class="box-header">
                <h3 class="box-title">Projects</h3>
                <div class="box-tools pull-right">
                    <!-- <button class="btn btn-primary btn-xs not-mine">Show not mine</button> -->
                    <!-- <button class="btn btn-primary btn-xs project-inactive">Show non-active</button> -->
                </div>
            </div>
            <div class="box-body table-responsive">
                <table class="table table-hover" id="projects-table">
                    <thead>
                    <tr>
                        <th class='proj'>Project</th>
                        <th class='cust'>Customer</th>
                        <th class='pm'>Proj. Mgr.</th>
                        <th class='people'>People</th>
                        <th class='tasks'>Tasks <small>(completed/total)</small></th>
                        <th class='ntask'>Next Task</th>
                        <th class='end'>Est. End Date</th>
                        <th class='status'>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for project in projects %}
                    <tr class="{% if not project.project_manager.name = user %}not-mine {% endif %}{% if project.status != project.ACTIVE %}project-inactive {% endif %}">
                        <td><a href="{% url 'pm:project-detail' project.id %}"></a>{{ project.name }}</td>
                        <td>{{ project.requester.full_name }} ({{ project.requester.group.name }})</td>
                        <td>{{ project.project_manager.full_name }}</td>
                        <td>{% for worker in project.worker_set.all %}{% if worker.owner %}<span class="bold">{% endif %}{{ worker.person.full_name }}{% if worker.owner %}</span>{% endif %}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                        <td>{{ project.completed_tasks.count }} - {{ project.task_set.all.count }}</td>
                        <td{% if project.next_tasks.count = 0 %} data-order="zzzzzzzz"{% endif %}>{% if project.next_tasks.count == 1 %}{% for task in project.next_tasks %}{{ task.name }} ({{ task.due_date | default_if_none:"<span class='text-yellow'>No due date</span>" }}){% endfor %}{% elif project.next_tasks.count == 0 %}<i class="text-yellow">No upcoming tasks defined</i>{% else %}<ol>{% for task in project.next_tasks %}<li>{{ task.name }} ({{ task.due_date }})</li>{% endfor %}</ol>{% endif %}</td>
                        <td data-order="{{ project.est_completion_date | date:"U" | default_if_none:"" }}">{{ project.est_completion_date }}</td>
                        <td><small class="badge {% if project.status = project.ACTIVE %}bg-green{% elif project.status = project.COMPLETED %}bg-blue{% elif project.status = project.ON_HOLD %}{% else %}bg-yellow{% endif %}">{{ project.get_status_display }}</small></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">People</h3>
            </div>
            <div class="box-body no-padding">
                <table class="table table-hover">
                    <tr>
                        <th>Individual</th>
                        <th>Project/Lead count</th>
                        <th>Total Tasks/due within 2 wks.</th>
                    </tr>
                    {% for person in peoples %}
                    <tr>
                        <td><a href="{% url 'pm:person-detail' person.id %}"></a>{{ person.full_name }}</td>
                        <td>{% if person.worker_set.count > 3 %}<span class="text-{% if person.worker_set.count > 5 %}red{% else %}yellow{% endif %}">{% endif %}{{ person.worker_set.count }}{% if person.worker_set.count > 3 %}</span>{% endif %} - {% if person.lead_count > 1 %}<span class="text-{% if person.lead_count > 2 %}red{% else %}yellow{% endif %}">{% endif %}{{ person.lead_count }}{% if person.lead_count > 1 %}</span>{% endif %}</td>
                        <td>{% if person.task_count > 7 %}<span class="text-{% if person.task_count > 11 %}red{% else %}yellow{% endif %}">{% endif %}{{ person.task_count }}{% if person.task_count > 8 %}</span>{% endif %} - {% if person.two_wk_task_count > 4 %}<span class="text-{% if person.two_wk_task_count > 6 %}red{% else %}yellow{% endif %}">{% endif %}{{ person.two_wk_task_count }}{% if person.two_wk_task_count > 4 %}</span>{% endif %}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Stats</h3>
            </div>
            <div class="box-body">
                <dt>We</dt>
                    <dl>are awesome</dl>
                <dt>If useful</dt>
                    <dl>we can show interesting stats on our own task completion rates and such</dl>
                <dt>Eventually</dt>
                    <dl>we can connect to Sharepoint and show Triage stats</dl>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block custom_js %}
$("tr").has("a").click(function() {
    window.location = $(this).find('a').attr('href');
}).hover(function() {
    $(this).toggleClass('hover');
});

$(document).ready( function () {
    $('#projects-table').DataTable();
} );
{% endblock custom_js %}

pm/templates/pm/project_new.html
{% extends "pm/base.html" %}
{% load crispy_forms_tags %}

{% block title %}New Project{% endblock %}

{% block content-header %}Create New Project{% endblock %}

{% block content %}
{% crispy form %}
{% endblock %}

{% block custom_js %}
$('.datemask input')
// date masking
    .inputmask('yyyy-mm-dd', {"placeholder": "yyyy-mm-dd"})
// add calendar icon
    .wrap('<div class="input-group"></div>')
    .before('<div class="input-group-addon"><i class="fa fa-calendar"></i></div>');
// make workers field pretty
$('#id_workers').select2({
    minimumInputLength: 2,
});
$('#hint_id_workers').remove();
{% endblock %}

pm/templates/pm/project_review.html
{% extends "pm/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Project Review{% endblock %}

{% block content-header %}Review Completed Projects{% endblock %}

{% block content %}
{% if project_empty %}
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger alert-dismissable">
            <h4>Problem!</h4>
            <p>This page was called without a project. Please verify the link. If everything looks OK, please contact the site administrator.</p>
        </div>
    </div>
</div>
{% elif project_active %}
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger alert-dismissable">
            <h4>Problem!</h4>
            <p>This project is still active and cannot yet be reviewed.</p>
        </div>
    </div>
</div>
{% else %}
<form action="{% url 'pm:reviews' project=project %}" id="reviews">
{% crispy project_form %}
{% for worker_form in worker_forms %}
    {% crispy worker_form %}
{% endfor %}
    <div class="row">
        <div class="col-md-12">
            <input type="submit" value="Submit">
        </div>
    </div>
</form>
{% endif %}
{% endblock %}

{% block custom_js %}
{% endblock %}